#!/usr/bin/env node
/**
 * Test catalog generator — a CENTRAL, static overview of which test cases exist
 * (for planning), independent of any run. Scans spec files across the
 * distributed locations and emits a feature × mode matrix + the full case list.
 *
 * Usage:
 *   node catalog.mjs                  # scans the dirs in SCAN below
 *   node catalog.mjs > TEST-CATALOG.md
 *
 * Add more roots (e.g. the private premium specs, or component-test dirs) to SCAN.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = path.dirname(fileURLToPath(import.meta.url));

// Locations to scan. Each: { label, root, glob, layer }. Missing roots are skipped,
// so this works even before the other repos are checked out alongside.
const SCAN = [
  { label: 'e2e (shared, public)', root: path.join(dir, 'specs'), match: /\.spec\.ts$/, layer: 'e2e' },
  { label: 'e2e premium (console-plus, private)', root: path.resolve(dir, '../console-plus/e2e/specs'), match: /\.spec\.ts$/, layer: 'e2e' },
  { label: 'component (console-components, public)', root: path.resolve(dir, '../console-components/src'), match: /\.(test|spec)\.ts$/, layer: 'component' },
  { label: 'component (console-plus-components, private)', root: path.resolve(dir, '../console-plus-components/src'), match: /\.(test|spec)\.ts$/, layer: 'component' },
];

const MODES = ['noauth', 'authn', 'authz', 'cedar'];

function walk(root, match, acc = []) {
  if (!fs.existsSync(root)) return acc;
  for (const e of fs.readdirSync(root, { withFileTypes: true })) {
    if (e.name === 'node_modules' || e.name.startsWith('.')) continue;
    const p = path.join(root, e.name);
    if (e.isDirectory()) walk(p, match, acc);
    else if (match.test(e.name)) acc.push(p);
  }
  return acc;
}

// Extract test cases: title, tags (@mode), fixme/skip status, and source line.
function parseFile(file) {
  const src = fs.readFileSync(file, 'utf8');
  const lines = src.split('\n');
  const cases = [];
  const re = /\b(?:test|it)(\.fixme|\.skip)?\s*\(\s*[`'"](.+?)[`'"]/;
  // nearest enclosing describe tags (simple: last describe seen above)
  let describeTags = [];
  lines.forEach((line, i) => {
    const d = line.match(/describe\s*\(\s*[`'"](.+?)[`'"]/);
    if (d) describeTags = [...(d[1].match(/@\w+/g) || [])];
    const m = line.match(re);
    if (m) {
      const title = m[2];
      const tags = [...new Set([...describeTags, ...(title.match(/@\w+/g) || [])])];
      cases.push({
        title: title.replace(/@\w+/g, '').replace(/\$\{.*?\}/g, '*').trim(),
        tags,
        status: m[1] ? m[1].slice(1) : 'active', // fixme | skip | active
        line: i + 1,
      });
    }
  });
  return cases;
}

// Logical journey order for spec files (a user's real flow), not alphabetical.
const SPEC_ORDER = [
  'bootstrap/bootstrap',
  'auth/login',
  'auth/noauth-access',
  'auth/logout',
  'smoke/route-smoke',
  'flows/warehouse-lifecycle',
  'flows/loqe',
  'flows/warehouse',
  'flows/role',
  'flows/governance-tags',
  'perms/access-control',
  'storage/cors',
];
const orderOf = (file) => {
  const i = SPEC_ORDER.findIndex((s) => file.includes(s));
  return i === -1 ? SPEC_ORDER.length : i;
};

const groups = [];
for (const s of SCAN) {
  const files = walk(s.root, s.match);
  if (!files.length) continue;
  const items = files.flatMap((f) =>
    parseFile(f).map((c) => ({ ...c, file: path.relative(s.root, f) })),
  );
  // e2e: order by the journey sequence (then by line); component: keep file/line.
  items.sort((a, b) =>
    s.layer === 'e2e'
      ? orderOf(a.file) - orderOf(b.file) || a.file.localeCompare(b.file) || a.line - b.line
      : a.file.localeCompare(b.file) || a.line - b.line,
  );
  if (items.length) groups.push({ ...s, items });
}

// --- render markdown ---
const out = [];
out.push('# Test Catalog', '');
out.push('_Static inventory of test cases for planning (generated by `catalog.mjs`, no run)._', '');

let total = 0,
  active = 0,
  pending = 0;

for (const g of groups) {
  out.push(`## ${g.label} — ${g.layer}`, '');
  if (g.layer === 'e2e') {
    out.push('| Spec | Case | ' + MODES.join(' | ') + ' | Status |');
    out.push('|---|---|' + MODES.map(() => '---').join('|') + '|---|');
    for (const c of g.items) {
      total++;
      c.status === 'active' ? active++ : pending++;
      const cells = MODES.map((m) => (c.tags.includes('@' + m) ? '✓' : ''));
      out.push(`| ${c.file} | ${c.title} | ${cells.join(' | ')} | ${c.status === 'active' ? '' : '🟡 ' + c.status} |`);
    }
  } else {
    out.push('| File | Case | Status |');
    out.push('|---|---|---|');
    for (const c of g.items) {
      total++;
      c.status === 'active' ? active++ : pending++;
      out.push(`| ${c.file} | ${c.title} | ${c.status === 'active' ? '' : '🟡 ' + c.status} |`);
    }
  }
  out.push('');
}

if (!groups.length) out.push('_No test files found in the scanned roots._', '');

out.push('---', `**${total} cases** — ${active} active, ${pending} pending (fixme/skip). Modes: ${MODES.join(', ')}.`);
const md = out.join('\n');
console.log(md);
fs.writeFileSync(path.join(dir, 'TEST-CATALOG.md'), md + '\n');

// --- also emit a standalone visual HTML overview (a stable "overview portal") ---
const esc = (s) => String(s).replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
const tick = (on) => (on ? '<span class="y">✓</span>' : '<span class="n">·</span>');
const sections = groups
  .map((g) => {
    const head =
      g.layer === 'e2e'
        ? `<tr><th>Spec</th><th>Case</th>${MODES.map((m) => `<th>${m}</th>`).join('')}<th>Status</th></tr>`
        : `<tr><th>File</th><th>Case</th><th>Status</th></tr>`;
    const rows = g.items
      .map((c) => {
        const status = c.status === 'active' ? '' : `<span class="fixme">${c.status}</span>`;
        if (g.layer === 'e2e') {
          const cells = MODES.map((m) => `<td class="c">${tick(c.tags.includes('@' + m))}</td>`).join('');
          return `<tr><td class="f">${esc(c.file)}</td><td>${esc(c.title)}</td>${cells}<td>${status}</td></tr>`;
        }
        return `<tr><td class="f">${esc(c.file)}</td><td>${esc(c.title)}</td><td>${status}</td></tr>`;
      })
      .join('');
    return `<h2>${esc(g.label)} <small>${g.layer}</small></h2><table>${head}${rows}</table>`;
  })
  .join('');
const html = `<!doctype html><meta charset="utf-8"><title>Test Catalog</title>
<style>
 body{font:14px/1.5 system-ui,sans-serif;margin:2rem auto;max-width:1100px;color:#1a1a2e;padding:0 1rem}
 h1{margin:0 0 .25rem} .sub{color:#667;margin:0 0 1.5rem}
 h2{margin:2rem 0 .5rem;font-size:1.05rem} h2 small{color:#88a;font-weight:400;font-size:.75rem;border:1px solid #ccd;border-radius:4px;padding:1px 6px;margin-left:6px}
 table{border-collapse:collapse;width:100%;margin-bottom:1rem;font-size:13px}
 th,td{border:1px solid #e3e3ef;padding:6px 10px;text-align:left} th{background:#f6f6fb;font-weight:600}
 td.c{text-align:center} td.f{color:#778;font-family:ui-monospace,monospace;font-size:12px}
 .y{color:#1a9d5a;font-weight:700} .n{color:#cfd2dd} .fixme{background:#fff3cd;color:#856404;border-radius:4px;padding:1px 6px;font-size:12px}
 .summary{margin-top:1.5rem;padding:.75rem 1rem;background:#f6f6fb;border-radius:8px}
</style>
<h1>Test Catalog</h1>
<p class="sub">What test cases exist (planning view, generated — no run). Results live in the Playwright report.</p>
${sections || '<p>No test files found.</p>'}
<p class="summary"><b>${total} cases</b> — ${active} active, ${pending} pending. A ✓ means that case runs in that auth mode; an empty cell is an uncovered scenario.</p>`;
fs.writeFileSync(path.join(dir, 'TEST-CATALOG.html'), html);
